// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Blog: typeof import('./components/Blog.vue')['default']
    Divider: typeof import('./components/Divider.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListBlogs: typeof import('./components/ListBlogs.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
